from typing import Protocol

from .game_protocol import GameProtocol


class DisplayProtocol(Protocol):
    last_message: str

    def getch(self) -> str | None: ...

    def clear(self) -> None: ...

    def refresh(self) -> None: ...

    def getmaxyx(self) -> tuple[int, int]: ...

    def move(self, new_y: int, new_x: int) -> None: ...

    def clrtoeol(self) -> None: ...

    def addstr(self, y: int, x: int, text: str) -> None: ...

    def set_display_limits(self, max_x: int, max_y: int) -> None: ...

    def set_message_line(self, y: int) -> None: ...

    def message(self, text: str, wait: bool = False) -> None: ...

    def run(self, game: GameProtocol) -> None: ...
