from typing import Protocol

from .game_protocol import GameProtocol

CTRL_C = "\x03"
ESCAPE = "\x1b"


class DisplayProtocol(Protocol):
    def getch(self) -> str | None: ...

    def clear(self) -> None: ...

    def refresh(self) -> None: ...

    def getmaxyx(self) -> tuple[int, int]: ...

    def move(self, new_y: int, new_x: int) -> None: ...

    def clrtoeol(self) -> None: ...

    def addstr(self, y: int, x: int, text: str) -> None: ...

    def message(self, text: str) -> None: ...

    def run(self, game: GameProtocol) -> None: ...
