"Not wearing armour." = "Not wearing armor."
"You aren't wearing any armour." = "You aren't wearing any armor."
"You can't wield armour." = "You can't wield armor."
"Your armour glows faintly for a moment." = "Your armor glows faintly for a moment."
"The wand releases a sluggish grey ray." = "The wand releases a sluggish gray ray."
"You suddenly feel much more skilful." = "You suddenly feel much more skillful."
"Wear armour" = "Wear armor"
"Take armour off" = "Take armor off"
