[config]
# Language Options
# en = English: UK, AU, NZ.
#      This is the English in the code, so there is no file for these languages.
# ca = Canadian English
# us = American Englilsh
# cn = Simplified Chinese (zh-CN)
# tw = Traditional Chinese (zh-TW)
# fr = French
# de = German
# th = Thai
language = "au"
terse = false
flush = false
jump = true
step = false
askme = false
showac = false
max_scores = 20
name = "JasonA"
fruit = ""
file = "vmclassic.toml"
version = "Vallis Magi Classic version 0.1"

[data_files]
armour = "armour.toml"
food = "food.toml"
potions = "potions.toml"
rings = "rings.toml"
scrolls = "scrolls.toml"
wands = "wands.toml"
weapons = "weapons.toml"

[[probabilities]]
name = "potions"
probability = 27

[[probabilities]]
name = "scrolls"
probability = 27

[[probabilities]]
name = "food"
probability = 18

[[probabilities]]
name = "weapons"
probability = 9

[[probabilities]]
name = "armour"
probability = 9

[[probabilities]]
name = "rings"
probability = 5

[[probabilities]]
name = "wands"
probability = 5
