# Default settings for all Armour.

[default.armour]
slot = "body"
is_armour = true

# Armour

[items.banded_mail]
weight = 22.0
priority = 7
armour_bonus = 7
armour_class = 4
movement_penalty = 3
stealth_penalty = 4
value = 90
probability = 10

[items.chain_mail]
weight = 18.0
priority = 5
armour_bonus = 5
armour_class = 5
movement_penalty = 2
stealth_penalty = 3
value = 75
probability = 12

[items.leather_armour]
weight = 8.0
priority = 1
armour_bonus = 1
armour_class = 8
movement_penalty = 0
stealth_penalty = 0
value = 5
probability = 20

[items.plate_mail]
weight = 25.0
priority = 8
armour_bonus = 8
armour_class = 3
movement_penalty = 4
stealth_penalty = 5
value = 400
probability = 5

[items.ring_mail]
weight = 12.0
priority = 2
armour_bonus = 2
armour_class = 7
movement_penalty = 1
stealth_penalty = 1
value = 30
probability = 15

[items.scale_mail]
weight = 14.0
priority = 4
armour_bonus = 4
armour_class = 6
movement_penalty = 2
stealth_penalty = 2
value = 3
probability = 13

[items.splint_mail]
weight = 20.0
priority = 6
armour_bonus = 6
armour_class = 4
movement_penalty = 3
stealth_penalty = 3
value = 80
probability = 10

[items.studded_leather]
weight = 12.0
priority = 3
armour_bonus = 3
armour_class = 7
movement_penalty = 1
stealth_penalty = 1
value = 15
probability = 15
