# Default settings for all Food.

[default.food]
tags = ["food"]
stackable = true
max_stack = 20
random_table = "food"


# Food

[items.food]
inherits = ["food"]
weight = 0.5
priority = 1
probability = 100
