# Default settings for all Potions.

[default.potions]
weight = 0.3
is_potion = true

# Mundane Potions

[items.potion_of_quench_thirst]
value = 50
priority = 14
probability = 1

# Magical Potions

[items.potion_of_extra_healing]
value = 180
priority = 10
probability = 5

[items.potion_of_haste_self]
value = 200
priority = 11
probability = 4

[items.potion_of_healing]
value = 130
priority = 6
probability = 15

[items.potion_of_magic_detection]
value = 105
priority = 8
probability = 6

[items.potion_of_monster_detection]
value = 120
priority = 7
probability = 6

[items.potion_of_raise_level]
value = 220
priority = 9
probability = 2

[items.potion_of_restore_strength]
value = 120
priority = 12
probability = 14

[items.potion_of_see_invisible]
value = 170
priority = 5
probability = 2

[items.potion_of_strength]
value = 150
priority = 4
probability = 15

# Cursed Magical Potions

[items.potion_of_blindness]
value = 50
priority = 13
probability = 4
cursed = true

[items.potion_of_confusion]
value = 50
priority = 1
probability = 8
cursed = true

[items.potion_of_paralysis]
value = 50
priority = 2
probability = 10
cursed = true

[items.potion_of_poison]
value = 50
priority = 3
probability = 8
cursed = true
