# Default settings for all Scrolls.

[default.scrolls]
weight = 0.1
max_stack = 20
stackable = true
is_scroll = true

# Mundane Scrolls

[items.scroll_blank]
scroll_type = "blank"
value = 50
priority = 15
probability = 1

# Magic Scrolls

[items.scroll_confuse_monster]
scroll_type = "confuse_monster"
value = 170
priority = 1
probability = 8

[items.scroll_enchant_armour]
scroll_type = "enchant_armour"
value = 130
priority = 6
probability = 8

[items.scroll_enchant_weapon]
scroll_type = "enchant_weapon"
value = 150
priority = 11
probability = 10

[items.scroll_genocide]
scroll_type = "genocide"
value = 200
priority = 16
probability = 1

[items.scroll_gold_detection]
scroll_type = "gold_detection"
value = 110
priority = 9
probability = 4

[items.scroll_hold_monster]
scroll_type = "hold_monster"
value = 200
priority = 4
probability = 2

[items.scroll_identify]
scroll_type = "identify"
value = 100
priority = 7
probability = 21

[items.scroll_light]
scroll_type = "light"
value = 100
priority = 3
probability = 10

[items.scroll_magic_mapping]
scroll_type = "magic_mapping"
value = 180
priority = 2
probability = 5

[items.scroll_remove_curse]
scroll_type = "remove_curse"
value = 105
priority = 13
probability = 8

[items.scroll_scare_monster]
scroll_type = "scare_monster"
value = 180
priority = 8
probability = 4

[items.scroll_teleportation]
scroll_type = "teleportation"
value = 175
priority = 10
probability = 7

# Cursed Scrolls

[items.scroll_aggravate_monsters]
scroll_type = "aggravate_monsters"
value = 60
priority = 14
probability = 1
cursed = true

[items.scroll_create_monster]
scroll_type = "create_monster"
value = 75
priority = 12
probability = 5
cursed = true

[items.scroll_sleep]
scroll_type = "sleep"
value = 50
priority = 5
probability = 5
cursed = true
